;;! target = "aarch64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -W memory64 -O static-memory-forced -O static-memory-guard-size=4294967295 -O dynamic-memory-guard-size=4294967295"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0xffff0000)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load8_u offset=0xffff0000))

;; wasm[0]::function[0]:
;;       stp     x29, x30, [sp, #-0x10]!
;;       mov     x29, sp
;;       ldr     x10, [x0, #0x60]
;;       add     x10, x10, x2
;;       mov     x11, #0xffff0000
;;       add     x10, x10, x11
;;       mov     x11, #0
;;       mov     x9, #0xffff
;;       cmp     x2, x9
;;       csel    x12, x11, x10, hi
;;       csdb
;;       strb    w3, [x12]
;;       ldp     x29, x30, [sp], #0x10
;;       ret
;;
;; wasm[0]::function[1]:
;;       stp     x29, x30, [sp, #-0x10]!
;;       mov     x29, sp
;;       ldr     x10, [x0, #0x60]
;;       add     x10, x10, x2
;;       mov     x11, #0xffff0000
;;       add     x10, x10, x11
;;       mov     x11, #0
;;       mov     x9, #0xffff
;;       cmp     x2, x9
;;       csel    x12, x11, x10, hi
;;       csdb
;;       ldrb    w0, [x12]
;;       ldp     x29, x30, [sp], #0x10
;;       ret
