;;! target = "s390x"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store offset=0xffff0000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load offset=0xffff0000))

;; wasm[0]::function[0]:
;;       lg      %r1, 8(%r2)
;;       lg      %r1, 0(%r1)
;;       la      %r1, 0xa0(%r1)
;;       clgrtle %r15, %r1
;;       stmg    %r8, %r15, 0x40(%r15)
;;       lgr     %r1, %r15
;;       aghi    %r15, -0xa0
;;       stg     %r1, 0(%r15)
;;       llilh   %r9, 0xffff
;;       lghi    %r3, 0
;;       llgfr   %r14, %r4
;;       llilf   %r8, 0xffff0004
;;       algfr   %r8, %r4
;;       jgnle   0x40
;;       lg      %r4, 0x68(%r2)
;;       ag      %r14, 0x60(%r2)
;;       agrk    %r2, %r14, %r9
;;       clgr    %r8, %r4
;;       locgrh  %r2, %r3
;;       strv    %r5, 0(%r2)
;;       lmg     %r8, %r15, 0xe0(%r15)
;;       br      %r14
;;
;; wasm[0]::function[1]:
;;       lg      %r1, 8(%r2)
;;       lg      %r1, 0(%r1)
;;       la      %r1, 0xa0(%r1)
;;       clgrtle %r15, %r1
;;       stmg    %r9, %r15, 0x48(%r15)
;;       lgr     %r1, %r15
;;       aghi    %r15, -0xa0
;;       stg     %r1, 0(%r15)
;;       llilh   %r9, 0xffff
;;       lghi    %r3, 0
;;       llgfr   %r14, %r4
;;       llilf   %r5, 0xffff0004
;;       algfr   %r5, %r4
;;       jgnle   0xac
;;       lg      %r4, 0x68(%r2)
;;       ag      %r14, 0x60(%r2)
;;       agrk    %r2, %r14, %r9
;;       clgr    %r5, %r4
;;       locgrh  %r2, %r3
;;       lrv     %r2, 0(%r2)
;;       lmg     %r9, %r15, 0xe8(%r15)
;;       br      %r14
