;;! target = "riscv64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -W memory64 -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store offset=0xffff0000)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load offset=0xffff0000))

;; wasm[0]::function[0]:
;;       addi    sp, sp, -0x10
;;       sd      ra, 8(sp)
;;       sd      s0, 0(sp)
;;       mv      s0, sp
;;       lui     a4, 0xffff
;;       slli    a1, a4, 4
;;       lui     a4, 0x3fffc
;;       addi    a5, a4, 1
;;       slli    a4, a5, 2
;;       add     a5, a2, a4
;;       bgeu    a5, a2, 8
;;       .byte   0x00, 0x00, 0x00, 0x00
;;       ld      a4, 0x68(a0)
;;       ld      a0, 0x60(a0)
;;       add     a0, a0, a2
;;       sltu    a2, a4, a5
;;       add     a0, a0, a1
;;       neg     a4, a2
;;       not     a1, a4
;;       and     a2, a0, a1
;;       sw      a3, 0(a2)
;;       ld      ra, 8(sp)
;;       ld      s0, 0(sp)
;;       addi    sp, sp, 0x10
;;       ret
;;
;; wasm[0]::function[1]:
;;       addi    sp, sp, -0x10
;;       sd      ra, 8(sp)
;;       sd      s0, 0(sp)
;;       mv      s0, sp
;;       lui     a4, 0xffff
;;       slli    a1, a4, 4
;;       lui     a3, 0x3fffc
;;       addi    a5, a3, 1
;;       slli    a3, a5, 2
;;       add     a5, a2, a3
;;       bgeu    a5, a2, 8
;;       .byte   0x00, 0x00, 0x00, 0x00
;;       ld      a3, 0x68(a0)
;;       ld      a0, 0x60(a0)
;;       add     a0, a0, a2
;;       sltu    a2, a3, a5
;;       add     a0, a0, a1
;;       neg     a4, a2
;;       not     a1, a4
;;       and     a2, a0, a1
;;       lw      a0, 0(a2)
;;       ld      ra, 8(sp)
;;       ld      s0, 0(sp)
;;       addi    sp, sp, 0x10
;;       ret
