;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store offset=0xffff0000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load offset=0xffff0000))

;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movl    $0xffff0000, %r10d
;;       xorq    %rax, %rax
;;       movl    %edx, %r11d
;;       movq    %r11, %r8
;;       addq    0x26(%rip), %r8
;;       jb      0x3a
;;   20: movq    0x68(%rdi), %r9
;;       addq    0x60(%rdi), %r11
;;       leaq    (%r11, %r10), %rdx
;;       cmpq    %r9, %r8
;;       cmovaq  %rax, %rdx
;;       movl    %ecx, (%rdx)
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   3a: ud2
;;   3c: addb    %al, (%rax)
;;   3e: addb    %al, (%rax)
;;   40: addb    $0, %al
;;
;; wasm[0]::function[1]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movl    $0xffff0000, %ecx
;;       xorq    %rax, %rax
;;       movl    %edx, %r11d
;;       movq    %r11, %rdx
;;       addq    0x27(%rip), %rdx
;;       jb      0x88
;;   6f: movq    0x68(%rdi), %r8
;;       addq    0x60(%rdi), %r11
;;       addq    %r11, %rcx
;;       cmpq    %r8, %rdx
;;       cmovaq  %rax, %rcx
;;       movl    (%rcx), %eax
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   88: ud2
;;   8a: addb    %al, (%rax)
;;   8c: addb    %al, (%rax)
;;   8e: addb    %al, (%rax)
;;   90: addb    $0, %al
