;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -O static-memory-maximum-size=0 -O static-memory-guard-size=4294967295 -O dynamic-memory-guard-size=4294967295"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0xffff0000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load8_u offset=0xffff0000))

;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movl    %edx, %edx
;;       movq    0x68(%rdi), %rax
;;       movq    %rdx, %r8
;;       addq    0x60(%rdi), %r8
;;       movl    $0xffff0000, %edi
;;       leaq    (%r8, %rdi), %r11
;;       xorq    %rdi, %rdi
;;       cmpq    %rax, %rdx
;;       cmovaq  %rdi, %r11
;;       movb    %cl, (%r11)
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;
;; wasm[0]::function[1]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movl    %edx, %ecx
;;       movq    0x68(%rdi), %rax
;;       movq    %rcx, %rdx
;;       addq    0x60(%rdi), %rdx
;;       movl    $0xffff0000, %edi
;;       leaq    (%rdx, %rdi), %r11
;;       xorq    %rdi, %rdi
;;       cmpq    %rax, %rcx
;;       cmovaq  %rdi, %r11
;;       movzbq  (%r11), %rax
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
