;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -W memory64 -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store offset=0xffff0000)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load offset=0xffff0000))

;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movl    $0xffff0000, %r8d
;;       xorq    %rax, %rax
;;       movq    %rdx, %r9
;;       addq    0x29(%rip), %r9
;;       jb      0x37
;;   1d: movq    0x68(%rdi), %r10
;;       addq    0x60(%rdi), %rdx
;;       leaq    (%rdx, %r8), %rdi
;;       cmpq    %r10, %r9
;;       cmovaq  %rax, %rdi
;;       movl    %ecx, (%rdi)
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   37: ud2
;;   39: addb    %al, (%rax)
;;   3b: addb    %al, (%rax)
;;   3d: addb    %al, (%rax)
;;   3f: addb    %al, (%rax, %rax)
;;
;; wasm[0]::function[1]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movl    $0xffff0000, %ecx
;;       xorq    %rax, %rax
;;       movq    %rdx, %r8
;;       addq    0x22(%rip), %r8
;;       jb      0x86
;;   6c: movq    0x68(%rdi), %r9
;;       addq    0x60(%rdi), %rdx
;;       leaq    (%rdx, %rcx), %rdi
;;       cmpq    %r9, %r8
;;       cmovaq  %rax, %rdi
;;       movl    (%rdi), %eax
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   86: ud2
;;   88: addb    $0, %al
